package com.bankclient.view;

import com.bankclient.Session;
//import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;


public class Main extends javax.swing.JFrame {

    /**
     * Creates new form MainInterface
     */
    public Main() {
        initComponents();
        lblAuthName.setText(Session.name() + " -- " + Session.accountNumber());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPaneMain = new javax.swing.JSplitPane();
        paneNavigate = new javax.swing.JPanel();
        navlbBankOps = new javax.swing.JLabel();
        navDepositOp = new javax.swing.JButton();
        navWithdrawalOp = new javax.swing.JButton();
        navHistory = new javax.swing.JButton();
        navTransfer = new javax.swing.JButton();
        dskPaneDesktop = new javax.swing.JPanel();
        lblAuthName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(Session.getBank().getName() + " Bank");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        paneNavigate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        splitPaneMain.setDividerLocation(600);
        splitPaneMain.setDividerSize(0);

        navlbBankOps.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        navlbBankOps.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        navlbBankOps.setText("BANK OPERATIONS");

        navDepositOp.setText("Deposit");
        navDepositOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navDepositOpActionPerformed(evt);
            }
        });

        navWithdrawalOp.setText("Withdrawal");
        navWithdrawalOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navWithdrawalOpActionPerformed(evt);
            }
        });

        navTransfer.setText("Transfer");
        navTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navTransferActionPerformed(evt);
            }
        });

        navHistory.setText("History");
        navHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneNavigateLayout = new javax.swing.GroupLayout(paneNavigate);
        paneNavigate.setLayout(paneNavigateLayout);
        paneNavigateLayout.setHorizontalGroup(
            paneNavigateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneNavigateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneNavigateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navlbBankOps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(navWithdrawalOp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(navDepositOp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(navHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(navTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                )
                .addContainerGap())
        );
        paneNavigateLayout.setVerticalGroup(
            paneNavigateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneNavigateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navlbBankOps)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navDepositOp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navWithdrawalOp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navTransfer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navHistory)
                .addContainerGap())
        );

        lblAuthName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAuthName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAuthName.setText("Authenticated user name");


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAuthName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paneNavigate, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paneNavigate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAuthName)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }


    private void navDepositOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navDepositOpActionPerformed
        // Create a new Operation Dialog and show it
        new DepositOperation(this, true).setVisible(true);
    }

    private void navWithdrawalOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navWithdrawalOpActionPerformed
        // Create a new Withdrawal Dialog and show it
        new WithdrawOperation(this, true).setVisible(true);
    }

    private void navTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navWithdrawalHisActionPerformed
        // Create a new WithdrawalDetails Dialog and show it
        new TransferOperation(this, true).setVisible(true);
    }

    private void navHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navTransferActionPerformed
        // Create a new History Dialog and show it
        new History(this, true).setVisible(true);
    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int i = JOptionPane.showConfirmDialog(this, "Are you sure you want to close? ", "Select One", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the System look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            String systemLookAndFeel = javax.swing.UIManager.getSystemLookAndFeelClassName();
            javax.swing.UIManager.setLookAndFeel(systemLookAndFeel);
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            System.out.println("Error: " + e);
        }
        //</editor-fold>
        //</editor-fold>
        java.awt.EventQueue.invokeLater(() -> {
            Login login = new Login();
            login.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            login.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dskPaneDesktop;
    private javax.swing.JLabel lblAuthName;
    private javax.swing.JButton navTransfer;
    private javax.swing.JButton navDepositOp;
    private javax.swing.JButton navHistory;
    private javax.swing.JButton navWithdrawalOp;
    private javax.swing.JLabel navlbBankOps;
    private javax.swing.JPanel paneNavigate;
    private javax.swing.JSplitPane splitPaneMain;
    // End of variables declaration//GEN-END:variables
}
